const CONFIG = {
    introTitle: 'Đình Đình ơi !',
    introDesc1: 'Nếu em hỏi hình gì đẹp nhất? Anh sẽ trả lời hình như chúng mình. Nếu anh là nhà thơ anh sẽ viết tặng em những vần thơ cháy bỏng. Nếu anh là nhạc sỹ anh sẽ viết tặng em những bản tình ca bất hủ. Nếu anh là lập trình viên anh sẽ viết nên những đoạn mã ngập tràn hương vị tình yêu. Và nếu anh có thể, anh sẽ làm tất cả vì em.',
    btnIntro: '<i class="fa-solid fa-heart"></i>',
    title: 'Đình Đình hỡiiiiiiii🙄',
    desc: 'Anh không rõ từ khi nào nữa? Nhưng có lẽ từ khi gặp em, Anh cảm thấy cuộc đời của anh dường như tốt lên hẳn. Mọi thứ xung quanh anh ngày càng có nhiều màu sắc hơn trước. Điều đặc biệt là anh cảm thấy bản thân mình chính chắn và có trách nhiệm nhiều hơn, hơn hết anh cảm thấy mình biết yêu nhiều hơn. Anh không rõ vì lý do nào, nhưng lúc nào anh cũng muốn được yêu, được lo, được chiều chuộng, chăm sóc người mình thương. Em biết không dường như cả lý trí và con tim anh dường như mách bảo: "Không ai khác ngoài em cả, chắc chắn chỉ có thể là em và mỗi em". Anh biết lúc anh nói điều này trước đó với em có phần hơi vội khiến em nghĩ anh xấu xa và có thể không đàng hoàng, vì anh move on quá lẹ khi vừa mới kết thúc một mối tình xong. Nghĩ lại anh thấy anh đã sai khi quyết định nói điều quan trọng với em một cách vội vã như thế! Anh thật lòng xin lỗi em rất nhiều, anh đã tự dành cho mình khoảng thời gian dài sau đó để kiểm chứng! Nhưng mà thật sự thì anh nghĩ mình đã yêu em thật, anh không thể ngừng suy nghĩ về e dù chỉ là một giây hay một phút, lúc nào trong đầu của anh vẫn là hình bóng của em và vang bên tai vẫn luôn là giọng của em nhất là khi em chúc anh ngủ ngon. Cứ mỗi từng giây, từng phút anh đều luôn đợi màn hình dth sáng hiện lên dòng thông báo messenger từ em. Có nhiều đêm anh thức rất khuya, ngay cả khi buồn ngủ, nhưng anh vẫn cố gắng kìm chế cơn ngủ chỉ đợi chờ tin nhắn từ mỗi em vì anh nghĩ nếu anh lỡ mất một cơ hội nào từ em thì chắc sẽ hông còn cơ hội nào khác đến với anh nữa! Đơn giản vì anh yêu em thật lòng! Dù không được gặp em sớm hơn, càng không phải là người đầu tiên, nhưng anh chỉ hy vọng RẰNG:"Em sẽ là cô gái cuối cùng của anh! Anh sẽ nỗ lực, cố gắng mọi thứ để có thể lo được cho em. Anh mong rằng em sẽ cho anh một cơ hội! Hãy cùng nhau chia sẽ mọi cảm xúc, khó khăn mà ta gặp phải. Hãy cùng nhau xử lý và giải quyết tất cả vấn đề đó. Và hãy cùng anh viết tiếp những trang khác đến hết cuộc đời em nhé 🩷"',
    btnYes: '🩷Dạ🩷 ',
    btnNo: 'Không ❤️‍🩹',
    question:'Thế giới hơn 7 tỉ người mà sao em lại yêu anh <3',
    btnReply: 'Gửi cho anh 🩷',
    reply: 'Yêu thì yêu mà không yêu thì yêu <3333333333333333333',
    mess: 'Anh biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Mặc váy vào đi tối anh qua đón nhé công chúa.',
    btnAccept: 'Dạ okiii lun 🩷',
    messLink: 'https://web.facebook.com/messages/t/100023091787133' 
}